device:
    desc: The device to perform training on
    value: cpu
model:
    value:
        num_hidden_layers: 3
        hidden_layer_size: 36
training:
    value:
        epochs: 30
        learning_rate: 1.0e-3
data:
    value:
        mat_file_name: Flatgroundwalking_20220802
        batch_size: 8192
        num_past_history: 3
        state_description_name: v1
        actuator_name: all
plot:
    value: True